name: Update README stats cards

on:
  schedule:
    # Runs automatically every 12 hours
    - cron: "0 */12 * * *"
  # Allows you to manually trigger the update at any time
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
          
      # 1. Generates the Top Languages Card
      - name: Generate Top Languages Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=mmmedea&layout=compact&bg_color=030014&title_color=A855F7&text_color=9ca3af&hide_border=true
          path: profile/top-langs.svg

      # 2. Generates the Activity Graph
      - name: Generate Activity Graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: mmmedea
          options: bg_color=030014&color=9ca3af&line=A855F7&point=ffffff&area=true&hide_border=true
          output_path: profile/activity-graph.svg

      # 3. Generates the GitHub Streak Stats
      - name: Generate GitHub Streak Stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=mmmedea&theme=dark&background=030014&ring=A855F7&fire=A855F7&currStreakNum=ffffff&sideNums=9ca3af&currStreakLabel=9ca3af&sideLabels=9ca3af&dates=9ca3af&hide_border=true
          path: profile/streak-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update all GitHub stats and badges" || exit 0
          git push