name: Update README stats cards

on:
  schedule:
    # Runs automatically every 12 hours
    - cron: "0 */12 * * *"
  # Allows you to manually trigger the update at any time
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      # Generates the main GitHub Stats Card
      - name: Generate GitHub Stats Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=mmmedea&show_icons=true&bg_color=030014&title_color=A855F7&text_color=9ca3af&icon_color=A855F7&hide_border=true
          
      # Generates the Top Languages Card
      - name: Generate Top Languages Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=mmmedea&layout=compact&bg_color=030014&title_color=A855F7&text_color=9ca3af&hide_border=true

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update README stats cards" || exit 0
          git push